## font
font_family      IBM Plex Mono
font_size 12.0

enabled_layouts *
window_margin_width 0
placement_strategy top-left

# colors
include ./colors/wallpaper-dark.conf

background_tint 0
allow_remote_control yes

enable_wayland_display_detection yes

map kitty_mod+enter new_window_with_cwd
