#!/home/goldberg/.venv/bin/python

import sys
import colorgram

from pathlib import Path
from PIL import ImageColor

class ExtractColors:
    """
        Extract 18 colors from the image.
    """
    # path to the image
    image : Path

    # lists containing colors in rgb and hex format
    colors_rgb : list[tuple]
    colors_hex : list[str]

    def __init__(self, image : Path) -> None:
        self.image = image
        self.__extract_colors()

    @staticmethod
    def __rgb_to_hex(rgb : tuple[int, int, int]):
        """
            Convert rgb tuple into hex string.

            :param rgb tuple
            :return hex string
        """
        return "#{:02x}{:02x}{:02x}".format(rgb[0], rgb[1], rgb[2])

    def __extract_colors(self):
        """
            Extract 18 most common colors from the image.
        """
        print(f'extracting colors from {self.image}...')
        extracted_colors = colorgram.extract(self.image, 17)
        print(f'colors extracted.')
        for color in extracted_colors:
            self.colors_rgb.append(color.rgb)
            self.colors_hex.append(ExtractColors.__rgb_to_hex(
                                                        color.rgb))

class ParseColors:
    """
        Parse colors lists into dictionary with key being
        name of the colors and value the color itself.

        eg. { background : #ffffff }
    """
    # path to the image
    image : Path

    # color extractor
    extract_color : ExtractColors

    # color dictionaries
    color_entries_hex : dict[str, str]
    color_entries_rgb : dict[str, tuple[int, int, int]]


    def __init__(self, image) -> None:
        self. image = image
        extract_colors = ExtractColors(self.image)
        self.__parse_colors(extract_colors.colors_hex)
        self.__parse_colors(extract_colors.colors_rgb)

    def __parse_rgb(self, colors : list):
        """
            Parses RGB colors into dictionary.
        """
        self.color_entries_rgb = { 'background' : colors[0],
                                   'foreground' : colors[3],
                                   'cursor'     : colors[3],
                                   'color0'     : colors[0],
                                   'color1'     : colors[1],
                                   'color2'     : colors[2] }
        # filling colors3-15
        for i in range(4, 17):
            color_number='color' + str(i - 1)
            self.color_entries_rgb[color_number] = colors[i]

    def __parse_hex(self, colors : list):
        """
            Parses RGB colors into dictionary.
        """
        self.color_entries_hex = { 'background' : colors[0],
                                   'foreground' : colors[3],
                                   'cursor'     : colors[3],
                                   'color0'     : colors[0],
                                   'color1'     : colors[1],
                                   'color2'     : colors[2] }
        # filling colors3-15
        for i in range(4, 17):
            color_number='color' + str(i - 1)
            self.color_entries_hex[color_number] = colors[i]


    def __parse_colors(self, colors : list):
        """
            Parses generated_colors into 3 special colors and 15 basic ones,
            defining how terminal and programs within it look.
        """
        if type(colors[0]) is tuple:
            self.__parse_rgb(colors)
        else:
            self.__parse_hex(colors)

def __gen_colored_str_block(rgb_tuple):
    """
        Generates colored string using ANSI escape characters (four spaces).
    """
    color_code = f"\033[48;2;{rgb_tuple[0]};{rgb_tuple[1]};{rgb_tuple[2]}m" 
    reset_code = "\033[0m" 
    return f'{color_code}    {reset_code}'

def __get_colored_str_block(hex : str):
    """
        Returns colored string in the color given by hex
    """
    return __gen_colored_str_block(ImageColor.getcolor(hex, 'RGB'))

def print_opt(k : str, v : str):
    print('{:<12}{:<12}'.format(k, __get_colored_str_block(v)))


def print_colored_block(rgb_tuple):
    """
        Prints four spaces with coloured background, using ANSI format.
    """
    print(__gen_colored_str_block(rgb_tuple))

def write_kitty_conf(color_dictionary : dict [str, str]):
    """
        Writes given config into proper .conf file with name
        colors-kitty-<image_name>.conf within $HOME/.config/kitty/colors
        directory.
    """

    # name of the provided image
    image_name = Path(sys.argv[2]).stem

    # name of the generated config file
    config_name ='colors-kitty-' + image_name + '.conf'

    # path to the new configuration file
    config_path = Path.joinpath(
        Path.home(),
        '.config',
        'kitty',
        'colors',
        str(config_name)
    )

    print(f'writing generated config...')

    with open(config_path, 'w') as kitty_colors:
        for k,v in color_dictionary.items():
            kitty_colors.write('{:<12}{:<12}'.format(k, v) + '\n')
            print_opt(k, v)

    print(f'config written to {config_path}.')

def gen_css(color_dictionary : dict [str, str]):
    """
        Writes given config into css colors file to $HOME/.config/eww/styles/_colors-<image-name>.scss.
    """

    # name of the provided image
    image_name = Path(sys.argv[2]).stem

    # name of the generated config file
    css_name ='colors-' + image_name + '.scss'

    # path to the new configuration file
    css_path = Path.joinpath(
        Path.home(),
        '.config',
        'eww',
        'styles',
        str(css_name)
    )

    print(f'writing generated colors as {css_name}...')

    with open(css_path, 'w') as css_colors:
        for k,v in color_dictionary.items():
            css_colors.write('${:<12} : {:<7}'.format(k, v) + '\n')
            print_opt(k, v)

    print(f'config written to {css_path}.')

def gen_kitty_conf(generated_colors):
    """
        Parses generated_colors into 3 special colors and 15 basic ones,
        defining how terminal and programs within it look.
    """
    conf = {'background' : generated_colors[0],
            'foreground' : generated_colors[3],
            'cursor'     : generated_colors[3],
            'color0'     : generated_colors[0],
            'color1'     : generated_colors[1],
            'color2'     : generated_colors[2]}

    # filling colors3-15
    for i in range(4, 17):
        color_number='color' + str(i - 1)
        conf[color_number] = generated_colors[i]

    #write_kitty_conf(conf)
    gen_css(conf)

def __rgb_to_hex(rgb_tuple):
    return "#{:02x}{:02x}{:02x}".format(rgb_tuple[0], rgb_tuple[1], rgb_tuple[2])

def extract_colors():
    generated_colors = colorgram.extract(Path(sys.argv[2]), 17)
    colors = []
    for color in generated_colors:
        colors.append(__rgb_to_hex(color.rgb))

    gen_kitty_conf(colors)

def __remove_redundant_splits(split, output):
    for s in split:
        if s != '':
            output.append(s)
    return output

def __clean_split_list(split):
    cleaned_split = []
    cleaned_split = __remove_redundant_splits(split, cleaned_split)
    cleaned_split[1] = cleaned_split[1].replace('\n', '')
    return cleaned_split

def __retrieve_data(line, conf):
    """
        Splipts the line of the config file by space, removes empty elements
        and newline sequences.
    """
    split_line = line.split(' ')
    clear_split = __clean_split_list(split_line)
    conf[clear_split[0]] = clear_split[1]

def __display_configuration(conf):
    for k, v in conf.items():
        print_opt(k, v)

def list_colors():
    """
        In case user modifier the config manually, script reads the colors 
        directly from given file on the drive after the parameter -l.
    """
    # config from the drive
    conf = Path(sys.argv[2])

    # retrieved data
    retrieved_conf = {}

    # reading data and properly parsing it into dictionary
    with open(conf, 'r') as kitty_colors:
        for line in kitty_colors:
            __retrieve_data(line, retrieved_conf)

    __display_configuration(retrieved_conf)

if __name__ == "__main__":
    if sys.argv[1] == '-g':
        extract_colors()
    elif sys.argv[1] == '-l':
        list_colors()
    elif sys.argv[1] == '-c':
        list_colors()
    else:
        print('usage: extract-colors [[-g] | [-l]] [file]')
        print('\t-g [file] generates most abundant colors in the given file (image) and writes them into kitty config (as a separate file).')
        print('\t-l [file] parses given color configuration for kitty terminal, and displays both the names and corresponding hue.')
