# ---- wallpaper-derived color scheme ----

# basic
foreground #e8d0c4
background #281C21
selection_foreground #281C21
selection_background #9A5669

# cursor
cursor #e8d0c4
cursor_text_color #281C21

# url
url_color #CC7282

# normal colors
color0  #281C21
color1  #D5686E
color2  #7b9b7b
color3  #E08F76
color4  #6B4C60
color5  #9A5669
color6  #CC7282
color7  #e8d0c4

# bright colors
color8  #5A3653
color9  #F6AB8E
color10 #8bab8b
color11 #F6AB8E
color12 #8F374E
color13 #CC7282
color14 #d4b8ac
color15 #f5e6dd

# tab bar
active_tab_foreground   #281C21
active_tab_background   #9A5669
inactive_tab_foreground #d4b8ac
inactive_tab_background #3C3344
